import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "../firebase";
import "./Features.css";

export default function Features() {
  const navigate = useNavigate();
  const [user, setUser] = useState(null);
  const [checkingAuth, setCheckingAuth] = useState(true);

  // 🔐 Check login state
  useEffect(() => {
    const unsub = onAuthStateChanged(auth, (currentUser) => {
      setUser(currentUser);
      setCheckingAuth(false);
    });

    return () => unsub();
  }, []);

  // 🧠 Feature click logic
  const handleCardClick = (title) => {
    if (checkingAuth) return;

    if (title === "AI-Powered Study Schedule") {
      if (!user) {
        navigate("/login");
      } else {
        navigate("/dashboard");
      }
    }
  };

  const features = [
    ["📅", "AI-Powered Study Schedule", "Personalized daily plans generated by AI."],
    ["🎓", "Personal AI Tutor", "Understands your strengths & weaknesses."],
    ["🔄", "Adaptive Planning", "Rebalances plans automatically when tasks are missed."],
    ["📊", "Progress Dashboard", "Visual analytics for your performance."],
    ["💡", "AI Insights", "Weekly improvement suggestions powered by AI."],
    ["📈", "Performance Prediction", "Predicts exam readiness before deadlines."],
    ["⏰", "Smart Reminders", "Adaptive reminders based on your habits."],
    ["♻️", "Missed Session Recovery", "Automatically redistributes pending work."],
    ["🔥", "Deep Focus Mode", "Distraction-free studying with timers & breaks."],
    ["🏆", "Gamification", "Earn badges, streaks & stay motivated."],
    ["🧘", "Burnout Detection", "AI detects overload and suggests rest."],
    ["📅", "Calendar Sync", "Syncs with Google Calendar & avoids clashes."]
  ];

  return (
    <section id="features" className="features-section">
      <h2 className="features-title">Powerful AI Features</h2>

      <p className="features-subtitle">
        Everything you need to study smarter, stay consistent, and reach your academic goals.
      </p>

      <div className="features-grid">
        {features.map(([icon, title, desc], i) => (
          <div
            key={i}
            className="feature-card"
            onClick={() => handleCardClick(title)}
            title={
              title === "AI-Powered Study Schedule"
                ? user
                  ? "Open Dashboard 🚀"
                  : "Login required 🔒"
                : "Coming soon"
            }
          >
            <div className="feature-icon">{icon}</div>
            <h3 className="feature-heading">{title}</h3>
            <p className="feature-desc">{desc}</p>
          </div>
        ))}
      </div>
    </section>
  );
}
